image: node:20

definitions:
  services:
    docker:
      memory: 3072

pipelines:
  branches:
    main:
      - step:
          name: Unit tests, Lint & Build
          script:
            - yarn cache clean
            - yarn install --frozen-lockfile
            - yarn lint
            - yarn build
#            - yarn test -- --passWithNoTests
      - step:
          name: Build docker container (Staging)
          deployment: stage1
          size: 2x
          script:
            - >
              docker build . -t $AWS_ECR_REPOSITORY
              --build-arg ENV_FILE=.env.stage
            - pipe: 'atlassian/aws-ecr-push-image:1.1.0'
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                IMAGE_NAME: $AWS_ECR_REPOSITORY
            - pipe: atlassian/ssh-run:0.4.0
              variables:
                SSH_USER: 'ubuntu'
                SERVER: $SERVER_IP
                SSH_KEY: $SSH_KEY
                MODE: 'script'
                COMMAND: 'scripts/launch_staging.sh'
                DEBUG: 'true'
    develop:
      - step:
          name: Unit tests, Lint & Build
          script:
            - yarn cache clean
            - yarn install --frozen-lockfile
            - yarn lint
            - yarn build
#            - yarn test -- --passWithNoTests
      - step:
          name: Build docker container (Development)
          deployment: dev1
          script:
            - >
              docker build . -t $AWS_ECR_REPOSITORY
              --build-arg ENV_FILE=.env.dev
            - pipe: 'atlassian/aws-ecr-push-image:1.1.0'
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                IMAGE_NAME: $AWS_ECR_REPOSITORY
            - pipe: atlassian/ssh-run:0.4.0
              variables:
                SSH_USER: 'ubuntu'
                SERVER: $SERVER_IP
                SSH_KEY: $SSH_KEY
                MODE: 'script'
                COMMAND: 'scripts/launch_dev.sh'
                DEBUG: 'true'
          services:
            - docker